#!/bin/bash
#SBATCH -t 12:00:00
#SBATCH -N 10
#SBATCH --ntasks-per-node 96
#SBATCH -p standard96
#SBATCH -A hhpnhytt

module load intel/2022.2.1 impi/2021.7.1

export SLURM_CPU_BIND=none
export I_MPI_PIN_RESPECT_CPUSET=off
export I_MPI_DEBUG=6
export MKL_SERIAL=yes
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1


EDdir="path"
muArray=(mu1 mu2)
length=${#muArray[@]}
U=
B=
q=
t=
tPri=
tPriPri=
kSteps=
version=
bathSites=


cd $EDdir
#first mu
echo $length
cd "$EDdir/Nevalinna_U${U}_B${B}_q${q}_mu${muArray[0]}_t${t}_tPri${tPri}_tPriPri${tPriPri}_kSteps${kSteps}_version${version}_bathSites${bathSites}/EDCodeCorrect/"
cp hubb.andpar_bak hubb.andpar
mpiifort ed_dmft_parallel_frequencies_corrected_and_commented_betterSampling_november.f -o run.x -qmkl
mpirun -np 960 ./run.x > run.out
cd ..
cd ..

imu=1
while [ $imu -le $((length - 1)) ]  #length - 1 since -le less or equal to
do
    echo $imu
    echo ${muArray[$imu]}
    cd "$EDdir/Nevalinna_U${U}_B${B}_q${q}_mu${muArray[$imu]}_t${t}_tPri${tPri}_tPriPri${tPriPri}_kSteps${kSteps}_version${version}_bathSites${bathSites}/EDCodeCorrect/"
    #copy old EDresult to new dir
    cp "$EDdir/Nevalinna_U${U}_B${B}_q${q}_mu${muArray[$imu - 1]}_t${t}_tPri${tPri}_tPriPri${tPriPri}_kSteps${kSteps}_version${version}_bathSites${bathSites}/EDCodeCorrect//hubb.andpar" hubb.andpar_bak
    #change mu in "new" andpar to have correct andpar
    sed -i "23s/.*/  ${muArray[$imu]}          #chemical potential/g" hubb.andpar_bak
    cp hubb.andpar_bak hubb.andpar
    mpiifort ed_dmft_parallel_frequencies_corrected_and_commented_betterSampling_november.f -o run.x -qmkl
    mpirun -np 960 ./run.x > run.out         #--oversubscribe
    cd ..
    cd ..
    imu=$((imu+1))
done
